language: ruby
addons:
  postgresql: '9.3'
deploy:
  provider: heroku
  api_key:
    secure: QV2brmhdEtyjJgcQ3h8Z1oA6C5U2HeKEbKD5eeGUqNMsbeFUGfx2c/kWMzu8S4i4Iv7Ofpz9qSPoSEmzr++1hIb+4M1NInslB7Mhk1FQb5O9QwA6A3SmKnZ5iFdnnz/rUSj7+Dohl5owgzsgrkLgdi0eSTXl+n5AlcQy5B5jkuk=
  app: helpcue
  on:
    repo: aomra015/helpcue
